const constants = {
    CHANGE_MAIN_IMAGE: 'CHANGE_MAIN_IMAGE',
    LOAD_IMAGES_TO_IMAGE_CATALOG: 'LOAD_IMAGE_TO_IMAGE_CATALOG',
    CHANGE_DATA_INTERVAL_IN_IMAGE_CATALOG: 'CHANGE_DATA_INTERVAL_IN_IMAGE_CATALOG',
    ITEMS_COUNTER_FOR_ONE_ITERATION: 'ITEMS_COUNTER_FOR_ONE_ITERATION',
    LOADER_IN_IMAGE_CATALOG: 'LOADER_IN_IMAGE_CATALOG',

    NASA_QUERY: 'https://api.nasa.gov/planetary/apod',
    NASA_API_KEY: 'gKbcjyL1faO8B1GgXaE8hFzUqelAUaBhk1ZjIxLQ',
    NASA_API_KEY_STRING: 'api_key',
    NASA_TARGET_DATE_STRING: 'date',
    NASA_START_DATE_STRING: 'start_date',
    NASA_END_DATE_STRING: 'end_date',
    MEDIA_TYPE_IMAGE: 'image',
    MEDIA_TYPE_VIDEO: 'video',
    LOCAL_STORAGE_KEY: 'all-data',
    ITEMS_ON_PAGE: 24
}

export default constants
