const constants = {
    SET_TODAY_DATA: 'SET_TODAY_DATA',
    CHANGE_MAIN_IMAGE: 'CHANGE_MAIN_IMAGE',

    LOAD_IMAGES_TO_IMAGE_CATALOG: 'LOAD_IMAGE_TO_IMAGE_CATALOG',
    LOAD_IMAGES_FOR_ONE_ITERATION_TO_IMAGE_CATALOG: 'LOAD_IMAGE_FOR_ONE_ITERATION_TO_IMAGE_CATALOG',
    CHANGE_DATA_INTERVAL_IN_IMAGE_CATALOG: 'CHANGE_DATA_INTERVAL_IN_IMAGE_CATALOG',
    ITEMS_COUNTER_FOR_ONE_ITERATION: 'ITEMS_COUNTER_FOR_ONE_ITERATION',
    LOADER_IN_IMAGE_CATALOG: 'LOADER_IN_IMAGE_CATALOG',

    SET_STATE_FOR_MODAL_WINDOW: 'SET_STATE_FOR_MODAL_WINDOW',
    SET_TITLE_FOR_MODAL_WINDOW: 'SET_TITLE_FOR_MODAL_WINDOW',
    SET_MAIN_DATA_FOR_MODAL_WINDOW: 'SET_MAIN_DATA_FOR_MODAL_WINDOW',
    SET_DATE_FOR_MODAL_WINDOW: 'SET_DATE_FOR_MODAL_WINDOW',
    SET_EXPLANATION_FOR_MODAL_WINDOW: 'SET_EXPLANATION_FOR_MODAL_WINDOW',

    NASA_QUERY: 'https://api.nasa.gov/planetary/apod',
    NASA_API_KEY: 'gKbcjyL1faO8B1GgXaE8hFzUqelAUaBhk1ZjIxLQ',
    NASA_API_KEY_STRING: 'api_key',
    NASA_TARGET_DATE_STRING: 'date',
    NASA_START_DATE_STRING: 'start_date',
    NASA_END_DATE_STRING: 'end_date',
    MEDIA_TYPE_IMAGE: 'image',
    MEDIA_TYPE_VIDEO: 'video',
    TODAY: 'today',
    LOCAL_STORAGE_KEY: 'all-data',
    ITEMS_ON_PAGE: 24,

    MAIN_IMAGE_ATTRIBUTE: 'main-image'
}

export default constants
